// Generated by CoffeeScript 1.9.1
(function() {
  var cl, mssql;

  cl = console.log;

  mssql = require('mssql');

  mssql.connect('mssql://sa:mStartup!24@52.78.177.44:1433/dasuploader').then(function() {
    return new mssql.Request().query('select * from dasuploader.dasuploader').then(function(recordset) {
      cl('recordset');
      cl(recordset);
      return mssql.close();
    })["catch"](function(err) {
      cl('err');
      cl(err.toString());
      return mssql.close();
    });
  })["catch"](function(err) {
    cl(err.toString());
    return mssql.close();
  });

}).call(this);
